### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by tufi** [bemer/containers-on-aws-workshop#6]
File: https://github.com/bemer/containers-on-aws-workshop/tree/master/02-CreatingDockerImage

The link to "Setup Environment tutorial" in the following sentence is broken:

> In this tutorial, we assume that you completed the Setup Environment tutorial and:

Target is: 
https://github.com/bemer/containers-on-aws-workshop/blob/master/01-SetupEnvironment

Should be: 

https://github.com/bemer/containers-on-aws-workshop/blob/master/01-EnvironmentSetup/

**Comment by bemer** [comment]
Just fixed. Thank you!
